# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03d2261838b504c8860090cbe1b1886269ca58bb7fbd0d9fd88e61f137ae796e0414edf0c8b769b602abd5e448231b92f22b883e05f8a9ceaa37720b09578df5

test:
  secret_key_base: b1fc774fa694759fb9acf61b65267f4c809cdd3fcf0128edff38eaab1c61d62f70602fde1f6f910c5bb17f08404ce65b78d7717215f194f816b7d26f218e3d6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
